### PR TITLE
Added sv.json

### PR DESCRIPTION
**Pull request by el97**
Added Swedish translation.

### CODE REVIEW

**Comment by fewieden** [comment]
hi @el97 please send your pull request to the develop branch. You don't need to create a new one, you can edit it here on github

**Comment by el97** [comment]
Done!

**Comment by fewieden** [comment]
Hi @el97 you forgot to add the new language file also to the js file, I will do that for you. Just keep it in mind in case you are going to translate more modules.

**Comment by el97** [comment]
Oh my bad... I will think of that later on.

**Comment by fewieden** [comment]
No worries, thank you for your contribution

**Pull request merged**
